[package]
name = "rtmate-server"
version = "0.1.0"
edition = "2021"

[dependencies]
rtmate-common = { path = "../rtmate-common"}

axum = { workspace = true, features = ["http2", "ws", "tokio", "macros"] }
axum-server = { workspace = true, features = ["tls-rustls"] }
tokio = { workspace = true, features = ["full"] }
# tokio-tungstenite = { workspace = true}
tower-http = { workspace = true, features = ["trace"] }
tracing = { workspace = true }
tracing-subscriber = { workspace = true, features = ["env-filter", "local-time"] }
dotenvy = {workspace = true }
serde_json = { workspace = true }
serde = {workspace = true, features = ["derive"] }
anyhow = { workspace = true }
hmac = { workspace = true }
sha2 = { workspace = true }
hex = { workspace = true }
uuid = { workspace = true, features = ["v4"] }
jsonwebtoken = { workspace = true }
chrono = { workspace = true }
diesel = { workspace = true, features = ["postgres", "chrono"]}
async-trait = { workspace = true }
base64 = "0.22"
time = { workspace = true }
tracing-log = { workspace = true }
dashmap = { workspace = true }
futures-util = { workspace = true }

[dev-dependencies]
criterion = { version = "0.5", features = ["async_tokio"] }

[[test]]
name = "broadcast_basic"
path = "tests/integration/broadcast_basic.rs"

[[test]]
name = "broadcast_performance"
path = "tests/integration/broadcast_performance.rs"

[[test]]
name = "broadcast_failure_isolation"
path = "tests/integration/broadcast_failure_isolation.rs"

[[test]]
name = "ws_pubsub"
path = "tests/integration/ws_pubsub.rs"

[[test]]
name = "auth_integration"
path = "tests/auth_integration.rs"

[[test]]
name = "auth_db_integration"
path = "tests/auth_db_integration.rs"

[[bench]]
name = "broadcast_bench"
path = "benches/broadcast_bench.rs"
harness = false



